version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    networks:
      - beam-demo
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data  
      - zookeeper-conf:/opt/zookeeper-3.4.13/conf
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    networks:
      - beam-demo
    ports:
      - 9092:9092
    volumes:
      - kafka:/kafka
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: ${hostname}
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.110 ## very important!!!!!!
      KAFKA_CREATE_TOPICS: "test:1:1" # create topic test
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  
  go-collect:
    image: go-collect:latest
    networks: 
      beam-demo:
    depends_on:
      - kafka

networks:
  beam-demo:

volumes:
  kafka: 
  zookeeper-data:
  zookeeper-conf: